### ISSUE TITLE
Return base64 string instead of saving the image

### ISSUE THREAD

**Issue by knownasilya** [zinserjan/wdio-screenshot#7]
Looks like the commands only save the image, but I don't want to save the image on the FS, since I'm
using it to build a PDF. Maybe expose the make* functions?

Thanks for this plugin!

**Comment by zinserjan** [comment]
All make* functions are already exported., see [index.js](https://github.com/zinserjan/wdio-screenshot/blob/master/src/index.js#L32).

In contrast to the normal save* commands you have to provide a WebdriverIO instance (browser)  as first parameter instead of a filename.

Perhaps it makes sense to make the filename optional like WebdriverIO's saveScreenshot command.

**Comment by knownasilya** [comment]
Yes. Is this compatible with v4 of webdriver.io?

**Comment by zinserjan** [comment]
Yes, like defined in [package.json](https://github.com/zinserjan/wdio-screenshot/blob/795624672a80e9921c25ba9bc9bab44fb1022a5e/package.json#L28)

**Comment by zinserjan** [comment]
fileName is optional now

released as [0.3.0](https://github.com/zinserjan/wdio-screenshot/releases/tag/v0.3.0) (#39)
